export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d2d9f4",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#8593a6",
        "on-secondary-fixed-variant": "#003ea7",
        "tertiary": "#091726",
        "secondary": "#0051d5",
        "secondary-container": "#346cef",
        "on-surface": "#131b2e",
        "on-background": "#131b2e",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dae2fc",
        "inverse-surface": "#283044",
        "success-green": "#16A34A",
        "on-secondary-fixed": "#00174b",
        "on-error": "#ffffff",
        "surface-container": "#eaedff",
        "surface-variant": "#dae2fc",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#0e1d2b",
        "inverse-primary": "#b5c4ff",
        "surface-container-lowest": "#ffffff",
        "warning-orange": "#EA580C",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "primary-fixed": "#dce1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "primary-container": "#00236f",
        "outline-variant": "#c5c5d3",
        "on-surface-variant": "#444651",
        "tertiary-container": "#1e2c3b",
        "outline": "#757682",
        "primary": "#001142",
        "background": "#faf8ff",
        "surface-container-high": "#e1e7ff",
        "glass-white": "rgba(255, 255, 255, 0.7)",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#dbe1ff",
        "on-tertiary-fixed-variant": "#3a4858",
        "on-primary-fixed": "#00164e",
        "surface-tint": "#425aa6",
        "surface": "#faf8ff",
        "tertiary-fixed": "#d5e4f8",
        "on-primary-container": "#778ede",
        "surface-bright": "#faf8ff",
        "surface-container-low": "#f2f3ff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eef0ff",
        "on-primary-fixed-variant": "#29428c",
        "tertiary-fixed-dim": "#b9c8db",
        "primary-fixed-dim": "#b5c4ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap-sm": "2rem",
        "section-gap-lg": "5rem",
        "gutter": "1.5rem",
        "container-max": "1280px",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "headline-4xl-mobile": ["Plus Jakarta Sans"],
        "body-base": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "display-xl": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-4xl": ["Plus Jakarta Sans"],
        "headline-3xl": ["Plus Jakarta Sans"],
        "headline-2xl": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-4xl-mobile": ["30px", {"lineHeight": "38px", "fontWeight": "700"}],
        "body-base": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-xl": ["60px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-xl": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-4xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-3xl": ["30px", {"lineHeight": "38px", "fontWeight": "700"}],
        "headline-2xl": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
